name: device_widgets
description: Yonomi Device Widgets
version: 1.0.2
homepage: https://www.yonomi.co

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  provider: ^4.3.3
  flutter:
    sdk: flutter
  yonomi_platform_sdk: ^1.0.2

dev_dependencies:
  mockito: ^4.1.4
  flutter_test:
    sdk: flutter