name: yonomi_device_widgets
description: Yonomi Device Widgets
version: 2.10.2
homepage: https://www.yonomi.co

environment:
  sdk: ">=2.16.0 <3.0.0"

flutter:
  uses-material-design: true

dependencies:
  provider: ^6.0.1
  flutter:
    sdk: flutter
  bootstrap_icons: ^1.9.1
  yonomi_platform_sdk: ^5.2.0
  built_value: ^8.1.4
  flutter_colorpicker: ^1.0.3
  modal_bottom_sheet: ^2.0.1

dev_dependencies:
  mockito: ^5.0.15
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
