name: yonomi_device_widgets
description: Yonomi Device Widgets
version: 2.6.0
homepage: https://www.yonomi.co

environment:
  sdk: '>=2.12.0 <3.0.0'

flutter:
  uses-material-design: true

dependencies:
  provider: ^6.0.1
  flutter:
    sdk: flutter
  bootstrap_icons: ^1.7.2
  yonomi_platform_sdk:
    git:
      url: https://github.com/Yonomi/yonomi-sdk-dart
      ref: DX-248_display_fanMode

dev_dependencies:
  mockito: ^5.0.15
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
