name: yonomi_device_widgets
description: Yonomi Device Widgets
version: 2.3.0
homepage: https://www.yonomi.co

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  provider: ^6.0.1
  flutter:
    sdk: flutter
  bootstrap_icons: ^1.5.0
  yonomi_platform_sdk:
    git:
      url: git://github.com/Yonomi/yonomi-sdk-dart.git
      ref: DX-252_battery_level_trait

dev_dependencies:
  mockito: ^5.0.15
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
