version: 2.1

#####################
# Common Definitions
#####################

# Orb declarations
orbs:
  codecov: codecov/codecov@1.0.2

# Simple YAML anchors
aliases:
  - &project_dir "~/project"

commands:
  tests:
    description: "Run local unit tests"
    steps:
      - run:
          name: command to run unit tests
          command: flutter test --reporter json | tojunit --output test-results/dart-tests/device_widgets_unit_tests-report.xml
  run-test-coverage:
    description: "Run all tests"
    steps:
      - run:
          name: command to run all tests
          command: flutter test --coverage
      - codecov/upload:
          file: coverage/lcov.info
  dependencies:
    description: "Download dependencies and setup global packages"
    parameters:
      shell:
        type: string
        default: "/bin/bash --login -eo pipefail"
    steps:
      - checkout
      - run:
          name: Download deps
          shell: << parameters.shell >>
          command: pub get
      - run:
          name: Get junitreporter
          shell: << parameters.shell >>
          command: pub global activate junitreport
      - run: export PATH="$PATH":"$HOME/.pub-cache/bin"

######################
# Workflow Definition
######################
workflows:
  version: 2.1
  test-and-build:
    jobs:
      - test

##################
# Job Definitions
##################
jobs:
  test:
    docker:
      - image: cirrusci/flutter:stable
    steps:
      - dependencies:
          shell: "/bin/bash -eo pipefail"
      - run:
          name: Make folder for test results
          command: mkdir -p test-results/dart-tests
      - tests
      - run-test-coverage
      - store_test_results:
          path: test-results
